name: Analyze code

on:
  push:
    branches:
      - "dev"
    paths:
      - "cdl_downloader**"
  pull_request:
    branches:
      - "dev"
      - "main"
    paths:
      - "cdl_downloader**"

jobs:
  analyze:
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Go to app directory
      run: cd cdl_downloader
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Analysing the code with pylint
      run: pylint --exit-zero $(git ls-files '*.py')